### ISSUE TITLE
Can't run on Ubuntu 20.04 and 18.04

### ISSUE THREAD

**Issue by xixixihaha** [labsyspharm/ashlar#102]
Tried the ashlar on both Ubuntu 18.04 and 20.04 both failed with the exception

Cycle 0:
    reading 1.jpg
Traceback (most recent call last):
  File "/home/simon/.local/bin/ashlar", line 8, in <module>
    sys.exit(main())
  File "/home/simon/.local/lib/python3.8/site-packages/ashlar/scripts/ashlar.py", line 171, in main
    return process_single(
  File "/home/simon/.local/lib/python3.8/site-packages/ashlar/scripts/ashlar.py", line 202, in process_single
    reader = build_reader(filepaths[0], plate_well=plate_well)
  File "/home/simon/.local/lib/python3.8/site-packages/ashlar/scripts/ashlar.py", line 328, in build_reader
    reader = reader_class(path, **kwargs)
  File "/home/simon/.local/lib/python3.8/site-packages/ashlar/reg.py", line 391, in __init__
    self.metadata = BioformatsMetadata(self.path)
  File "/home/simon/.local/lib/python3.8/site-packages/ashlar/reg.py", line 207, in __init__
    self._init_metadata()
  File "/home/simon/.local/lib/python3.8/site-packages/ashlar/reg.py", line 228, in _init_metadata
    options.setBoolean('zeissczi.autostitch', False)
  File "jnius/jnius_export_class.pxi", line 879, in jnius.JavaMethod.__call__
  File "jnius/jnius_conversion.pxi", line 72, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 205, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Integer' passed for a 'java/lang/Boolean'

Testing command:
ashlar 1.jpg 2.jpg --align-channel 0 --maximum-shift 50 --filter-sigma 1 -f ashlar_output_cycle{cycle}_channel{channel}.ome.tiff

Any clue to fix this?

**Comment by jmuhlich** [comment]
I think this is caused by kivy/pyjnius#124 so downgrading pyjnius should fix it. Pyjnius v1.2.1 or v1.3.0 should work. We will investigate how to work around this issue in ashlar so newer pyjnius versions will work too, or adjust our minimum compatible version if they fix the bug.

**Comment by xixixihaha** [comment]
@jmuhlich thanks so much! After downgrading pyjnius to 1.3.0 the issue solved.
