### ISSUE TITLE
Help in using Ashlar for registering different rounds of hybridization

### ISSUE THREAD

**Issue by pranathivemuri** [labsyspharm/ashlar#116]
Hi! Thanks for this cool repo in stitching and aligning. 

1. I am trying to use it on 4 test images I have. There are 2 nd2 stacks per 2 rounds of hybridization (4 in total). 
2.  2 test nd2 stacks per each round of hybridization which are 2 different field of views and need to be stitched 
3. The 2 different hybridization round stacks correspond to each other and need to be registered
5. Each nd2 stack has 5 channels and 150 z images. I am trying to register these 2 different rounds of hybridization and stitch the tiles within the same round

I want to figure out how Ashlar figures out which images to register and which images to stitch and how I should name my images accordingly, any feedback appreciated, thanks so much!

What I have done so far is 
1. I converted the nd2 files to tiff files for each image in zstack, so I have 150 images each with 5 channels. I have done this using imagej. Their naming looks something like below
round2_z001.tif..round2_z150.tif
round4_z00150.tif...round4_z00150.tif

3. Using the notebook from this link, I am trying to register similarly but seems like all the 150 images are getting stitched which is not what I intend to do, I want to register the round2, round4. I think it might be that Ashlar doesn't work on pre-stitched images that this isn't working? I will add the stitchable images in the tiff files soon and try again
https://github.com/labsyspharm/ashlar/issues/95 
```
readers = []
for i in [2, 4]:
    readers.append(fileseries.FileSeriesReader(
        './data_to_test/',
        pattern='round'+str(i)+'_Z{series}.tiff',
        overlap=0.15,
        width=10,
        height=10,
        layout='snake',
        direction='horizontal',
        pixel_size=0.1625,
    ))


# check if filenames are indexed properly
print(
    '\n'.join(readers[0].metadata.filename(i, 0) for i in range(80, 120))
)
# it's very likely you'll want `flip_x=False, flip_y=True`
# try not to tweak here for now
# process_axis_flip(c1r, flip_x=False, flip_y=False)


# If using the third channel, pass `channel=2` (0-based indexing in python)
thumbnail_c1r = thumbnail.make_thumbnail(readers[0], channel=0)

plt.figure()
# doing log just for visualization
plt.imshow(np.log(thumbnail_c1r))
```

**Comment by jmuhlich** [comment]
Ashlar only does 2D alignment, so just pick one Z level for now to test with -- probably somewhere in the middle like Z=75, assuming the focus is good there. Later you can use the transformations determined by Ashlar to shift each stack together as a whole. Now extract a 5-channel TIFF at the chosen Z level from each stack. Name the TIFFs with a common prefix for each round and use a sequential number for each field of view.  I will assume the following names for the commands below:
```
round_1_field_1.tif
round_1_field_2.tif
round_2_field_1.tif
round_2_field_2.tif
```
The `pattern` for round 1 will be `round_1_field_{series}.tif`. `width` is 2 and `height` is 1 (or 1 and 2 if your images are top-and-bottom instead of left-and-right). You will need to figure out what the overlap fraction and pixel size are based on your microscope acquisition setup (I'll just make up some values for now -- 10% overlap and 0.3 micron pixels). `layout` and `direction` aren't really relevant here since you only have 2 images and can be omitted. Run Ashlar from the command line as follows:
```
ashlar \
  'fileseries|/path/to/images|pattern=round_1_field_{series}.tif||width=2|height=1|overlap=0.1|pixel_size=0.3' \
  'fileseries|/path/to/images|pattern=round_2_field_{series}.tif||width=2|height=1|overlap=0.1|pixel_size=0.3' \
```
Note that we provide a 'fileseries' reader definition for each _round_, and each fileseries encompasses all of the _fields_ within that round. When Ashlar is finished, open `ashlar-output.ome.tif` and hopefully the result will be as you expect. If it looks good, we can proceed to writing a custom script to extend this to the full Z-stacks. If something looks wrong, I'll need to take a look at the images to diagnose the problem.

**Comment by pranathivemuri** [comment]
Hi @jmuhlich thanks so much for your reply! I wrote the below code to get my files formatted to the way you recommended and ran the ashlar command provided with one change having one | instead of || after .tif. I get the below error. I tried to debug it by testing if there is any nan, inf values, and turned all other program except for my terminal with 25 gb ram as per some solutions here https://stackoverflow.com/questions/21827594/raise-linalgerrorsvd-did-not-converge-linalgerror-svd-did-not-converge-in-m but I couldn't fix it. For some background there are 4 images in this folder for the one z stack with dimensions 2048, 2048 and have 5 channels not sure if they are too much for a 32 GB ram Lenovo legion machine. Any input/feedback much appreciated.

The good news is when I accidentally just did this on a single channel, the stitching worked and output looked very reasonable

```
import numpy as np
from nd2reader import ND2Reader
from skimage.io import imsave


def save_z_frame(nd2_path, z_index, save_path):
    file = ND2Reader(nd2_path)
    frames = []
    num_channels = len(file.metadata["channels"])
    for ith_channel in range(num_channels):
        frames.append(file.get_frame_2D(c=ith_channel, t=0, z=0, x=0, y=0, v=0))
    img = np.dstack(frames)
    del frames
    imsave(save_path, img)
    array_sum = np.sum(img)
    array_has_nan = np.isnan(array_sum)
    print(array_has_nan)
    array_has_inf = np.isinf(array_sum)
    print(array_has_inf)
    print(img.shape)    
    del img

# TODO automate this too using glob os 
left_path_round1 = "/home/pranathi/Downloads/nd2s/round2_A3-001.nd2"
right_path_round1 = "/home/pranathi/Downloads/nd2s/round2_A2-004.nd2"
left_path_round2 = "/home/pranathi/Downloads/nd2s/round4_A3-002.nd2"
right_path_round2 = "/home/pranathi/Downloads/nd2s/round4_A2-003.nd2"


# TODO Figure out this save z frame iteration when there is multiple field of views and tif name
save_z_frame(left_path_round1, 75, "round_1_field_1.tif")
save_z_frame(right_path_round1, 75, "round_1_field_2.tif")
save_z_frame(left_path_round2, 75, "round_2_field_1.tif")
save_z_frame(right_path_round2, 75, "round_2_field_2.tif")


# Merge this ashlar command line to python program - delete intermediate temp tifs
# For one z, after stitching and registering 4 images - what is the output data dimensions = 2 images of dimension 2048, 3789 4096-307(15%)
# ashlar 'fileseries|/home/pranathi/code/ashlar/testdata|pattern=round_1_field_{series}.tif|width=2|height=1|overlap=0.15|pixel_size=0.1625' 'fileseries|/home/pranathi/code/ashlar/testdata|pattern=round_2_field_{series}.tif|width=2|height=1|overlap=0.15|pixel_size=0.1625'
```

Error traceback

```
(ashlar) pranathi@legion:~/testdata$ ashlar 'fileseries|/home/pranathi/testdata|pattern=round_1_field_{series}.tif|width=2|height=1|overlap=0.15|pixel_size=0.1625' 'fileseries|/home/pranathi/testdata|pattern=round_2_field_{series}.tif|width=2|height=1|overlap=0.15|pixel_size=0.1625'
Stitching and registering input images
Cycle 0:
    reading fileseries|/home/pranathi/testdata|pattern=round_1_field_{series}.tif|width=2|height=1|overlap=0.15|pixel_size=0.1625
pattern=round_1_field_{series}.tif
width=2
height=1
overlap=0.15
pixel_size=0.1625
    assembling thumbnail 1/2/home/pranathi/miniconda3/envs/ashlar/lib/python3.9/site-packages/scikit_image-0.16.2-py3.9-linux-x86_64.egg/skimage/transform/_warps.py:103: RuntimeWarning: divide by zero encountered in true_divide
  factors = (np.asarray(input_shape, dtype=float) /
/home/pranathi/miniconda3/envs/ashlar/lib/python3.9/site-packages/numpy/core/_methods.py:179: RuntimeWarning: invalid value encountered in reduce
  ret = umr_sum(arr, axis, dtype, out, keepdims, where=where)
/home/pranathi/miniconda3/envs/ashlar/lib/python3.9/site-packages/scikit_image-0.16.2-py3.9-linux-x86_64.egg/skimage/transform/_geometric.py:63: RuntimeWarning: invalid value encountered in matmul
  new_pointsh = (matrix @ pointsh).T
Traceback (most recent call last):
  File "/home/pranathi/miniconda3/envs/ashlar/bin/ashlar", line 33, in <module>
    sys.exit(load_entry_point('ashlar==1.14.1+4.gdb26247.dirty', 'console_scripts', 'ashlar')())
  File "/home/pranathi/miniconda3/envs/ashlar/lib/python3.9/site-packages/ashlar-1.14.1+4.gdb26247.dirty-py3.9.egg/ashlar/scripts/ashlar.py", line 267, in main
    return process_single(
  File "/home/pranathi/miniconda3/envs/ashlar/lib/python3.9/site-packages/ashlar-1.14.1+4.gdb26247.dirty-py3.9.egg/ashlar/scripts/ashlar.py", line 314, in process_single
    edge_aligner.run()
  File "/home/pranathi/miniconda3/envs/ashlar/lib/python3.9/site-packages/ashlar-1.14.1+4.gdb26247.dirty-py3.9.egg/ashlar/reg.py", line 477, in run
    self.make_thumbnail()
  File "/home/pranathi/miniconda3/envs/ashlar/lib/python3.9/site-packages/ashlar-1.14.1+4.gdb26247.dirty-py3.9.egg/ashlar/reg.py", line 488, in make_thumbnail
    self.reader.thumbnail = thumbnail.make_thumbnail(
  File "/home/pranathi/miniconda3/envs/ashlar/lib/python3.9/site-packages/ashlar-1.14.1+4.gdb26247.dirty-py3.9.egg/ashlar/thumbnail.py", line 23, in make_thumbnail
    img_s = rescale(img, scale, multichannel=False, anti_aliasing=False)
  File "/home/pranathi/miniconda3/envs/ashlar/lib/python3.9/site-packages/scikit_image-0.16.2-py3.9-linux-x86_64.egg/skimage/transform/_warps.py", line 274, in rescale
    return resize(image, output_shape, order=order, mode=mode, cval=cval,
  File "/home/pranathi/miniconda3/envs/ashlar/lib/python3.9/site-packages/scikit_image-0.16.2-py3.9-linux-x86_64.egg/skimage/transform/_warps.py", line 157, in resize
    tform.estimate(src_corners, dst_corners)
  File "/home/pranathi/miniconda3/envs/ashlar/lib/python3.9/site-packages/scikit_image-0.16.2-py3.9-linux-x86_64.egg/skimage/transform/_geometric.py", line 684, in estimate
    _, _, V = np.linalg.svd(A)
  File "<__array_function__ internals>", line 180, in svd
  File "/home/pranathi/miniconda3/envs/ashlar/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 1648, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "/home/pranathi/miniconda3/envs/ashlar/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 97, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge
```

**Comment by pranathivemuri** [comment]
HI @jmuhlich Spoke too soon, just debugged my way from linalg to rescale and figured out that the tif should be structured with channels first and x, y next. If not the nan comes into one of the arrays while rescaling to estimate the transform resulting in above error. Doing that fixed the above error and ashlar ran fine! Sorry about the traceback and long messages above. 
Could you please point me in right direction for making the zstack work when you have time? It would be super helpful, thanks so much! Below is the updated code I just addded a rollaxis line.

The output for the one z looks great so far! I am excited to see what it would do on other zs and validate on other data that we have a stitched groundtruth for.

```
import numpy as np
from nd2reader import ND2Reader
from skimage.io import imsave


def save_z_frame(nd2_path, z_index, save_path):
    file = ND2Reader(nd2_path)
    frames = []
    num_channels = len(file.metadata["channels"])
    for ith_channel in range(num_channels):
        frames.append(file.get_frame_2D(c=ith_channel, t=0, z=0, x=0, y=0, v=0))
    img = np.dstack(frames)
    img = np.rollaxis(img, 2)
    del frames
    imsave(save_path, img)
    del img


# TODO automate this too using glob os
left_path_round1 = "/home/pranathi/Downloads/nd2s/round2_A3-001.nd2"
right_path_round1 = "/home/pranathi/Downloads/nd2s/round2_A2-004.nd2"
left_path_round2 = "/home/pranathi/Downloads/nd2s/round4_A3-002.nd2"
right_path_round2 = "/home/pranathi/Downloads/nd2s/round4_A2-003.nd2"


# TODO Figure out this save z frame iteration when there is multiple field of views and tif name
img1 = save_z_frame(left_path_round1, 0, "round_1_field_1.tif")
save_z_frame(right_path_round1, 0, "round_1_field_2.tif")
save_z_frame(left_path_round2, 0, "round_2_field_1.tif")
save_z_frame(right_path_round2, 0, "round_2_field_2.tif")


# Merge this ashlar command line to python program - delete intermediate temp tifs
# For one z, after stitching and registering 4 images - what is the output data dimensions = 2 images of dimension 2048, 3789 4096-307(15%)
# ashlar 'fileseries|/home/pranathi/code/ashlar/testdata|pattern=round_1_field_{series}.tif|width=2|height=1|overlap=0.15|pixel_size=0.1625' 'fileseries|/home/pranathi/code/ashlar/testdata|pattern=round_2_field_{series}.tif|width=2|height=1|overlap=0.15|pixel_size=0.1625'

```

**Comment by pranathivemuri** [comment]
@jmuhlich thanks for your answer above, I wanted to check-in on the z iteration question when you have time please, thank you!

**Comment by jmuhlich** [comment]
I'll assume your images don't need any alignment along the Z-axis, in other words the X,Y positions that Ashlar produces for one Z plane will be correct for all Z planes, per tile.  Here is a standalone script that will stitch your fileseries inputs and save the corrected X,Y positions to CSV files. I haven't tested it since I obviously don't have your files, but it's a straightforward usage of the Ashlar internal API that I've used many times... :sweat_smile:  If it works OK I can see about writing another one that will take the CSV files and your 4 .nd2 files and produce a single XYZC tiff.
```python
from ashlar.reg import EdgeAligner, LayerAligner
from ashlar.fileseries import FileSeriesReader
import numpy as np

reader1 = FileSeriesReader(
    "/home/pranathi/code/ashlar/testdata",
    pattern="round_1_field_{series}.tif",
    width=2,
    height=1,
    overlap=0.15,
    pixel_size=0.1625,
)
aligner1 = EdgeAligner(reader1, verbose=True)
aligner1.run()

reader2 = FileSeriesReader(
    "/home/pranathi/code/ashlar/testdata",
    pattern="round_2_field_{series}.tif",
    width=2,
    height=1,
    overlap=0.15,
    pixel_size=0.1625,
)
aligner2 = LayerAligner(reader2, aligner1, verbose=True)
aligner2.run()

np.savetxt("positions-1.csv", np.fliplr(aligner1.positions), delimiter=",", header="X,Y", comments="")
np.savetxt("positions-2.csv", np.fliplr(aligner2.positions), delimiter=",", header="X,Y", comments="")
```

**Comment by pranathivemuri** [comment]
Hi @jmuhlich Thanks so much for explaining and writing this script out. Sorry, it took me so long to run it - but happy to inform that it works. any help or direction for the next steps in directly using nd2s appreciated, thanks in advance!

**Comment by pranathivemuri** [comment]
@jmuhlich just pinging to see if I can get help with or direction for a script that will take the CSV files and the 4 .nd2 files and produce a single XYZC tiff.
