### ISSUE TITLE
How to make metadata when stitching jpg format tiles

### ISSUE THREAD

**Issue by zhusihan-python** [labsyspharm/ashlar#121]
Hello, i want to try ashlar to stitch jpg files into a whole slide image, but i don't know how to tell ashlar the location of each tiles.
my environment: win10 python3.7 ashlar 1.14.1
command:
`ashlar 000_005.jpg 000_006.jpg 000_007.jpg --output-channels 0 1 2 --pyramid -f final.ome.tiff`
input image:
![image](https://user-images.githubusercontent.com/23504604/165501363-8f08ba46-1afe-4bdd-a531-22edeec13f73.png)
output message:

```
Cycle 0:
    reading 000_005.jpg
WARNING: Stage coordinates undefined; falling back to (0, 0).
WARNING: Pixel size undefined; falling back to 1.0 μm.
    assembling thumbnail 1/1
    Channel 0:
        merging tile 1/1
WARNING: Pixel size undefined; falling back to 1.0 μm.
        writing to final.ome.tiff
    Channel 1:
        merging tile 1/1
        writing to final.ome.tiff
    Channel 2:
        merging tile 1/1
        writing to final.ome.tiff
Cycle 1:
    reading 000_006.jpg
WARNING: Stage coordinates undefined; falling back to (0, 0).
    assembling thumbnail 1/1
    estimated cycle offset [y x] = [515.  -8.]
    aligning tile 1/1
    Channel 0:
        merging tile 1/1
WARNING: Pixel size undefined; falling back to 1.0 μm.
        writing to final.ome.tiff
    Channel 1:
        merging tile 1/1
        writing to final.ome.tiff
    Channel 2:
        merging tile 1/1
        writing to final.ome.tiff
Cycle 2:
    reading 000_007.jpg
WARNING: Stage coordinates undefined; falling back to (0, 0).
    assembling thumbnail 1/1
    estimated cycle offset [y x] = [-81. -40.]
    aligning tile 1/1
    Channel 0:
        merging tile 1/1
WARNING: Pixel size undefined; falling back to 1.0 μm.
        writing to final.ome.tiff
    Channel 1:
        merging tile 1/1
        writing to final.ome.tiff
    Channel 2:
        merging tile 1/1
        writing to final.ome.tiff
Building pyramid
    Level 1:
        processing channel 9/9
    Level 2:
        processing channel 9/9
```
it seems ashlar need ome meta message to stitch,  the output single tiff file only has one channel of first image
![image](https://user-images.githubusercontent.com/23504604/165502176-02ae2840-6a32-46ff-8467-4d67c7c95372.png)
is there something wrong in my command, or lack of ome meta message?
if its the second reason, i have the coordinates and overlap of the tiles, how can i make the meta data to get ashlar works

**Comment by zhusihan-python** [comment]
@jmuhlich hello Mr Muhlich, i notice that you have support jpg and png formats recently, i test it and got some errors
my environment: win10 python3.9.13 ashlar 1.16.0
command:
`ashlar "fileseries|F:/ashlar_data|pattern=000_{series}.jpg|width=1|height=3|overlap=0.11" --flip-y -o ashlar-output.ome.tif
`
the errors:
```
Stitching and registering input images
Cycle 0:
    reading fileseries|F:/ashlar_data|pattern=000_{series}.jpg|width=1|height=3|overlap=0.11
Traceback (most recent call last):
  File "D:\softwares\py39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\softwares\py39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\softwares\py39\Scripts\ashlar.exe\__main__.py", line 7, in <module>
  File "D:\softwares\py39\lib\site-packages\ashlar\scripts\ashlar.py", line 212, in main
    return process_single(
  File "D:\softwares\py39\lib\site-packages\ashlar\scripts\ashlar.py", line 243, in process_single
    edge_aligner.run()
  File "D:\softwares\py39\lib\site-packages\ashlar\reg.py", line 485, in run
    self.compute_threshold()
  File "D:\softwares\py39\lib\site-packages\ashlar\reg.py", line 583, in compute_threshold
    img1 = self.reader.read(t1, self.channel)[offset1:offset1+w, :]
  File "D:\softwares\py39\lib\site-packages\ashlar\reg.py", line 428, in read
    img = self.reader.read(series, c)
  File "D:\softwares\py39\lib\site-packages\ashlar\fileseries.py", line 191, in read
    return skimage.io.imread(path, **kwargs)
  File "D:\softwares\py39\lib\site-packages\skimage\io\_io.py", line 53, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "D:\softwares\py39\lib\site-packages\skimage\io\manage_plugins.py", line 207, in call_plugin
    return func(*args, **kwargs)
  File "D:\softwares\py39\lib\site-packages\skimage\io\_plugins\imageio_plugin.py", line 15, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "D:\softwares\py39\lib\site-packages\imageio\v2.py", line 201, in imread
    return file.read(index=0, **kwargs)
  File "D:\softwares\py39\lib\site-packages\imageio\core\legacy_plugin_wrapper.py", line 145, in read
    reader = self.legacy_get_reader(**kwargs)
  File "D:\softwares\py39\lib\site-packages\imageio\core\legacy_plugin_wrapper.py", line 114, in legacy_get_reader
    return self._format.get_reader(self._request)
  File "D:\softwares\py39\lib\site-packages\imageio\core\format.py", line 220, in get_reader
    return self.Reader(self, request)
  File "D:\softwares\py39\lib\site-packages\imageio\core\format.py", line 311, in __init__
    self._open(**self.request.kwargs.copy())
TypeError: _open() got an unexpected keyword argument 'key'
```
as the skimage.io.imread didn't recognize 'key' kwargs, so i comment this part of read in fileseries.py
![image](https://user-images.githubusercontent.com/23504604/183428999-ed2be700-7fcd-409a-a7be-a7eaedca812b.png)
and pass as_gray=True to skimage.io.imread, then it runs successful with an tif output
![image](https://user-images.githubusercontent.com/23504604/183432238-1f986ab6-3d2d-4858-acc0-9f808e3c3de2.png)
so there is another question, how can i use the registration of the grayscale to apply it to rgb jpg file, finally i can get a rgb whole silde image

**Comment by jmuhlich** [comment]
The PNG/JPG support is not merged yet. I was waiting for code review from a colleague first. You can check out that specific branch to try out the feature, or wait until PR #139 is merged.
