### ISSUE TITLE
Exception: Can't handle non-square pixels (0.293388, 0.293389)

### ISSUE THREAD

**Issue by straussmaximilian** [labsyspharm/ashlar#122]
Hi,

I am trying to run ashlar as part of the mcmicro pipeline with nextflow.
However, I get a Command error related to non-square pixels.

```
Command error:
  WARNING: Stage coordinates' measurement unit is undefined; assuming μm.
  Traceback (most recent call last):
    File "/usr/local/bin/ashlar", line 8, in <module>
      sys.exit(main())
    File "/usr/local/lib/python3.7/dist-packages/ashlar/scripts/ashlar.py", line 184, in main
      args.quiet
    File "/usr/local/lib/python3.7/dist-packages/ashlar/scripts/ashlar.py", line 213, in process_single
      process_axis_flip(reader, flip_x, flip_y)
    File "/usr/local/lib/python3.7/dist-packages/ashlar/scripts/ashlar.py", line 302, in process_axis_flip
      _ = metadata.positions
    File "/usr/local/lib/python3.7/dist-packages/ashlar/reg.py", line 177, in positions
      return Metadata.positions.fget(self)[self.active_series]
    File "/usr/local/lib/python3.7/dist-packages/ashlar/reg.py", line 94, in positions
      self.tile_position(i) for i in range(self._num_images)
    File "/usr/local/lib/python3.7/dist-packages/ashlar/reg.py", line 94, in <listcomp>
      self.tile_position(i) for i in range(self._num_images)
    File "/usr/local/lib/python3.7/dist-packages/ashlar/reg.py", line 375, in tile_position
      position_pixels = position_microns / self.pixel_size
    File "/usr/local/lib/python3.7/dist-packages/ashlar/reg.py", line 292, in pixel_size
      % tuple(values))
  Exception: Can't handle non-square pixels (0.293388, 0.293389)
```
Reading the Parameters with ImageJ, we have the following values:

Width:  3705.8078 µm (12631)
Height:  4720.6434 µm (16090)
Size:  194MB
Resolution:  3.4084 pixels per µm
Pixel size: 0.2934x0.2934 µm^2

I think it would be fair to assume that this is a precision problem and the pixels are somewhat square. The display precision in ImageJ is sub-nanometer, and I think this would be a good cutoff. I would therefore propose to round to 4 decimals here.

Happy to make a small pull request with a proposed solution in case.

**Comment by jmuhlich** [comment]
Thanks for reporting this, I completely agree that the values should be rounded when comparing them for equality. I'll fix this and tag a new release right now -- watch for v1.15.3.
