### ISSUE TITLE
Failing to run "Exception: Unable to find JAVA_HOME"

### ISSUE THREAD

**Issue by josenimo** [labsyspharm/ashlar#152]
Dear ASHLAR team,

I followed the installation instructions and I cant seem to run anything with ashlar.. any help?
Thank you for this beautiful algorithm!

this is my stack trace:

(ashlar) PS C:\Users\jnimoca> ashlar -h
Traceback (most recent call last):
  File "C:\Users\jnimoca\Anaconda3\envs\ashlar\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jnimoca\Anaconda3\envs\ashlar\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jnimoca\Anaconda3\envs\ashlar\Scripts\ashlar.exe\__main__.py", line 4, in <module>
  File "C:\Users\jnimoca\Anaconda3\envs\ashlar\lib\site-packages\ashlar\scripts\ashlar.py", line 8, in <module>
    from .. import reg
  File "C:\Users\jnimoca\Anaconda3\envs\ashlar\lib\site-packages\ashlar\reg.py", line 39, in <module>
    import jnius
  File "C:\Users\jnimoca\Anaconda3\envs\ashlar\lib\site-packages\jnius\__init__.py", line 18, in <module>
    java = get_java_setup(sys.platform)
  File "C:\Users\jnimoca\Anaconda3\envs\ashlar\lib\site-packages\jnius\env.py", line 66, in get_java_setup
    JAVA_HOME = get_jdk_home(platform)
  File "C:\Users\jnimoca\Anaconda3\envs\ashlar\lib\site-packages\jnius\env.py", line 316, in get_jdk_home
    raise Exception('Unable to find JAVA_HOME')
Exception: Unable to find JAVA_HOME

Update:
It seems the problem is with the package pyjnius. So I went to their website to follow their installation instructions : (https://pyjnius.readthedocs.io/en/stable/installation.html) I did this and still get the same error.

**Comment by jmuhlich** [comment]
Could you provide the output from running `conda list` and `java -version`? Please wrap it in triple-backquotes or use the "add code" button in the comment editor so it is easier for us to read, thanks!

**Comment by josenimo** [comment]
Thank you for assisting, here is the data. I did try to run just following the instructions in the README, but then I tried to troubleshoot. 

Conda list:
```(ashlar) PS C:\Users\jnimoca> conda list
# packages in environment at C:\Users\jnimoca\Anaconda3\envs\ashlar:
#
# Name                    Version                   Build  Channel
ansicon                   1.89.0          py310h5588dad_5    conda-forge
aom                       3.4.0                h0e60522_1    conda-forge
asciitree                 0.3.3                      py_2
ashlar                    1.17.0                   pypi_0    pypi
blessed                   1.19.1          py310h5588dad_1    conda-forge
blosc                     1.21.1               h74325e0_3    conda-forge
brotli                    1.0.9                h2bbff1b_7
brotli-bin                1.0.9                h2bbff1b_7
bzip2                     1.0.8                he774522_0
c-blosc2                  2.3.1                hdf67494_0    conda-forge
ca-certificates           2022.9.14            h5b45459_0    conda-forge
certifi                   2022.9.14          pyhd8ed1ab_0    conda-forge
cfitsio                   4.1.0                h5a969a9_0    conda-forge
charls                    2.3.4                h39d44d4_0    conda-forge
cloudpickle               2.0.0              pyhd3eb1b0_0
cycler                    0.11.0             pyhd3eb1b0_0
cython                    0.29.32                  pypi_0    pypi
cytoolz                   0.11.0          py310h2bbff1b_0
dask-core                 2022.7.0        py310haa95532_0
dav1d                     1.0.0                h8ffe710_1    conda-forge
fasteners                 0.16.3             pyhd3eb1b0_0
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.12.1               h546665d_0    conda-forge
fsspec                    2022.7.1        py310haa95532_0
giflib                    5.2.1                h62dcd97_0
icu                       58.2                 ha925a31_3
imagecodecs               2022.8.8        py310hd634bd4_3    conda-forge
imageio                   2.19.3          py310haa95532_0
intel-openmp              2022.1.0          h59b6b97_3788
jinxed                    1.1.0           py310h5588dad_2    conda-forge
joblib                    1.1.0              pyhd3eb1b0_0
jpeg                      9e                   h2bbff1b_0
jxrlib                    1.1                  he774522_2
kiwisolver                1.4.2           py310hd77b12b_0
lcms2                     2.12                 h83e58a3_0
lerc                      4.0.0                h63175ca_0    conda-forge
libaec                    1.0.6                h39d44d4_0    conda-forge
libavif                   0.10.1               h8ffe710_1    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h2bbff1b_7
libbrotlidec              1.0.9                h2bbff1b_7
libbrotlienc              1.0.9                h2bbff1b_7
libcblas                  3.9.0              16_win64_mkl    conda-forge
libcurl                   7.84.0               h86230a5_0
libdeflate                1.13                 h8ffe710_0    conda-forge
libffi                    3.4.2                hd77b12b_4
liblapack                 3.9.0              16_win64_mkl    conda-forge
libpng                    1.6.37               h2a8f88b_0
libssh2                   1.10.0               hcd4344a_0
libtiff                   4.4.0                h8a3f274_0
libwebp-base              1.2.4                h8ffe710_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libzlib                   1.2.12               hcfcfb64_3    conda-forge
libzopfli                 1.0.3                ha925a31_0
locket                    1.0.0           py310haa95532_0
lz4-c                     1.9.3                h2bbff1b_1
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
matplotlib                3.5.3           py310h5588dad_2    conda-forge
matplotlib-base           3.5.3           py310h7329aa0_2    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
msgpack-python            1.0.3           py310h59b6b97_0
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4                      py_0
networkx                  2.8.6              pyhd8ed1ab_0    conda-forge
numcodecs                 0.7.3           py310hd77b12b_0
numpy                     1.23.3          py310h4a8f9c9_0    conda-forge
openjdk                   11.0.15              h57928b3_1    conda-forge
openjpeg                  2.4.0                h4fc8c34_0
openssl                   1.1.1q               h8ffe710_0    conda-forge
packaging                 21.3               pyhd3eb1b0_0
partd                     1.2.0              pyhd3eb1b0_1
pillow                    9.2.0           py310h767b3fd_1    conda-forge
pip                       22.2.2                   pypi_0    pypi
pthread-stubs             0.3                  h3c9f919_1
pyjnius                   1.4.2           py310h8684bd8_0    conda-forge
pyparsing                 3.0.9           py310haa95532_0
pyqt                      5.9.2           py310hd77b12b_6
python                    3.10.4               hbb2ffb3_0
python-dateutil           2.8.2              pyhd3eb1b0_0
python_abi                3.10                    2_cp310    conda-forge
pywavelets                1.3.0           py310h2bbff1b_0
pyyaml                    6.0             py310h2bbff1b_0
qt                        5.9.7            vc14h73c81de_0
scikit-image              0.19.3          py310hf5e1058_1    conda-forge
scipy                     1.9.1           py310h578b7cb_0    conda-forge
setuptools                65.3.0                   pypi_0    pypi
sip                       4.19.13         py310hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1
snappy                    1.1.9                h6c2663c_0
sqlite                    3.39.2               h2bbff1b_0
tbb                       2021.5.0             h59b6b97_0
threadpoolctl             2.2.0              pyh0d69192_0
tifffile                  2022.8.12          pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h2bbff1b_0
toolz                     0.11.2             pyhd3eb1b0_0
tornado                   6.2             py310h2bbff1b_0
tzdata                    2022c                h04d1e81_0
ucrt                      10.0.20348.0         haa95532_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.29.30139          h890b9b1_7    conda-forge
wcwidth                   0.2.5              pyhd3eb1b0_0
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2             py310haa95532_2
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.5                h8cc25b3_1
yaml                      0.2.5                he774522_0
zarr                      2.12.0             pyhd8ed1ab_0    conda-forge
zfp                       1.0.0                h0e60522_1    conda-forge
zlib                      1.2.12               h8cc25b3_3
zlib-ng                   2.0.6                h8ffe710_0    conda-forge
zstd                      1.5.2                h19a0ad4_0

# java -version:
(ashlar) PS C:\Users\jnimoca> java -version
openjdk version "11.0.15" 2022-04-19 LTS
OpenJDK Runtime Environment Zulu11.56+19-CA (build 11.0.15+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.56+19-CA (build 11.0.15+10-LTS, mixed mode)

**Comment by Yu-AnChen** [comment]
Weirdly I was only able to reproduce the issue with the latest `openjdk` build (`openjdk=11.0.15=h57928b3_2`) on my PC running Windows10

@josenimo could you try a different openjdk build? To do so, in your `ashlar` conda env, run

```bash
conda install openjdk=11.0.15=h57928b3_0 -c conda-forge -y
```

And if there's no error, this should also run fine (in your `ashlar` conda env)

```bash
python -c "import jnius"
```

---
I reproduced the issue with the following on my windows machine

```bash
conda create -n ashlar-issue python=3.10.4 pyjnius openjdk=11.0.15=h57928b3_2 -c conda-forge -y
conda activate ashlar-issue
python -c "import jnius"
```

And here's the error

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\yc296\Miniconda3\envs\ashlar-issue\lib\site-packages\jnius\__init__.py", line 42, in <module>
    raise Exception("Unable to create jni env, no jvm dll found.")
Exception: Unable to create jni env, no jvm dll found.
```

**Comment by josenimo** [comment]
@Yu-AnChen @jmuhlich thank you for your help

I am not sure what am I doing wrong, but it is still not working.
I am attaching the stack trace of what I am trying, with the conda list at the end.. 
[ASHLAR_conda_list.txt](https://github.com/labsyspharm/ashlar/files/9682446/ASHLAR_conda_list.txt)

let me know if there is anything else I could try

**Comment by Yu-AnChen** [comment]
Thanks @josenimo the terminal output is very helpful.

Interestingly I reproduced the issue in Anaconda Powershell Prompt while the Anaconda Prompt works fine

<img width="602" alt="image" src="https://user-images.githubusercontent.com/17751400/193309047-46b8b976-f921-4162-8aa9-9e246e867b36.png">

I haven't found a solution yet, please try Anaconda Prompt for now.

**Comment by josenimo** [comment]
Thanks, for now that works!
