### ISSUE TITLE
ValueError: images must be same shape

### ISSUE THREAD

**Issue by josenimo** [labsyspharm/ashlar#159]
Dear ASHLAR devs,

I am trying to run ashlar on tiles imaged from MACSima instrument, and for some reason I am not able to run it. This was the command I used: 
`ashlar --output ./output.tif --align-channel 0 "fileseries|.|pattern=Cycle_{cycle:3}_Channel_{channel:1}_Frame_{series:1}.tif|overlap=0.075|pixel_size=0.65|width=2|height=2|layout=snake"`

<details>
<summary>and the error I got</summary>
Stitching and registering input images
Cycle 0:
    reading fileseries|.|pattern=Cycle_{cycle:3}_Channel_{channel:1}_Frame_{series:1}.tif|overlap=0.075|pixel_size=0.65|width=2|height=2|layout=snake
Traceback (most recent call last):
  File "C:\Users\jnimoca\Jose_BI\Anaconda\envs\ashlar\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jnimoca\Jose_BI\Anaconda\envs\ashlar\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jnimoca\Jose_BI\Anaconda\envs\ashlar\Scripts\ashlar.exe\__main__.py", line 7, in <module>
  File "C:\Users\jnimoca\Jose_BI\Anaconda\envs\ashlar\lib\site-packages\ashlar\scripts\ashlar.py", line 212, in main
    return process_single(
  File "C:\Users\jnimoca\Jose_BI\Anaconda\envs\ashlar\lib\site-packages\ashlar\scripts\ashlar.py", line 243, in process_single
    edge_aligner.run()
  File "C:\Users\jnimoca\Jose_BI\Anaconda\envs\ashlar\lib\site-packages\ashlar\reg.py", line 484, in run
    self.compute_threshold()
  File "C:\Users\jnimoca\Jose_BI\Anaconda\envs\ashlar\lib\site-packages\ashlar\reg.py", line 584, in compute_threshold
    _, errors[i] = utils.register(img1, img2, self.filter_sigma, upsample=1)
  File "C:\Users\jnimoca\Jose_BI\Anaconda\envs\ashlar\lib\site-packages\ashlar\utils.py", line 23, in register
    shift = skimage.registration.phase_cross_correlation(
  File "C:\Users\jnimoca\Jose_BI\Anaconda\envs\ashlar\lib\site-packages\skimage\registration\_phase_cross_correlation.py", line 225, in phase_cross_correlation
    raise ValueError("images must be same shape")
ValueError: images must be same shape
</details>

conda list:
[ashlar_conda_list.txt](https://github.com/labsyspharm/ashlar/files/9969310/ashlar_conda_list.txt)

Here you can see my test files, and the jupyter notebook that I used to regex the filenames. 
https://filetransfer.mdc-berlin.de/?u=8Ek6pcgQ&p=7Xx3qkMZ

It is a simple 4 tile ROI. However it does follow a different imaging path (see image):
![image](https://user-images.githubusercontent.com/30318135/200785377-0589b97d-1ba5-42b5-bd4d-9f2e385f13df.png)

Thanks in advance for the help.
Best,
Jose

**Comment by Yu-AnChen** [comment]
Thanks for the detailed report and test images! I've filed a PR (#161) that fixes the error you are seeing. 

Note that your image layout requires adding `direction=vertical` to the ashlar call. I used the following call and generated the attached screenshot

```
ashlar --output ./output.ome.tif --align-channel 0 "fileseries|.|pattern=Cycle_{cycle:3}_Channel_{channel:1}_Frame_{series:1}.tif|overlap=0.075|pixel_size=0.65|width=2|height=2|layout=snake|direction=vertical"
```

![160](https://user-images.githubusercontent.com/17751400/201791560-561a4897-33be-4dc7-916a-e336980a70e7.jpg)

**Comment by josenimo** [comment]
Dear @Yu-AnChen, 
thank you for the help, the direction=vertical was perfect. 
I needed to downgrade to Ashlar 1.14.0 to not get the error.
Best,
Jose

**Comment by niovl** [comment]
Hi, I got the same error on my data. The data is like this,
![image](https://user-images.githubusercontent.com/22088591/204813942-fcb40907-6e80-437e-817d-6e341368f9cc.png)

script is like this，
`ashlar "fileseries|D:/data/large_chip/A6/test|pattern={series}.tif|width=3|height=1|overlap=0.1" --align-channel 0 -o output.tif`

**Comment by josenimo** [comment]
@niovl have you tried passing the layout argument? In your case it would be "raster"

**Comment by josenimo** [comment]
@niovl hmm I think I cant help you, I would have tried the same thing. I can try replicating the error. Could you upload the three images? What was your installation like? Also, what is the error message?

**Comment by niovl** [comment]
Hi, @josenimo 
<details close>
<summary>The error message</summary>
File "D:\apps\anaconda\setup\envs\ashlar\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\apps\anaconda\setup\envs\ashlar\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\apps\anaconda\setup\envs\ashlar\Scripts\ashlar.exe\__main__.py", line 7, in <module>
  File "D:\apps\anaconda\setup\envs\ashlar\lib\site-packages\ashlar\scripts\ashlar.py", line 212, in main
    return process_single(
  File "D:\apps\anaconda\setup\envs\ashlar\lib\site-packages\ashlar\scripts\ashlar.py", line 243, in process_single
    edge_aligner.run()
  File "D:\apps\anaconda\setup\envs\ashlar\lib\site-packages\ashlar\reg.py", line 484, in run
    self.compute_threshold()
  File "D:\apps\anaconda\setup\envs\ashlar\lib\site-packages\ashlar\reg.py", line 584, in compute_threshold
    _, errors[i] = utils.register(img1, img2, self.filter_sigma, upsample=1)
  File "D:\apps\anaconda\setup\envs\ashlar\lib\site-packages\ashlar\utils.py", line 23, in register
    shift = skimage.registration.phase_cross_correlation(
  File "D:\apps\anaconda\setup\envs\ashlar\lib\site-packages\skimage\registration\_phase_cross_correlation.py", line 225, in phase_cross_correlation
    raise ValueError("images must be same shape")
ValueError: images must be same shape
</details>

The three images：
[test.zip](https://github.com/labsyspharm/ashlar/files/10129419/test.zip)

**Comment by niovl** [comment]
Hi， @Yu-AnChen ，Hope to get your help.
