### ISSUE TITLE
Windows and Docker error

### ISSUE THREAD

**Issue by smith6jt-cop** [labsyspharm/ashlar#208]
Hello,

Testing on a 63 image set of BaSiC-corrected images: 0000.tif - 0062.tif.  Using latest Docker image and enter from admin cmd:

docker run -v %cd%:/input -v %cd%:/ashlar -it labsyspharm/ashlar:latest ashlar "fileseries|/input|pattern={series:4}.tif|overlap=0.3|pixel_size=0.377454|width=7|height=9|layout=snake|direction=horizontal" -o /ashlar --output-channels 0

Getting:

WARNING: The output path must include a filename with a .tif or .tiff suffix. Specifying only a directory path with -o/--output has been deprecated and will be disabled in a future version. See the -o documentation for details.
Stitching and registering input images
Cycle 0:
    reading fileseries|/input|pattern={series}.tif|overlap=0.3|pixel_size=0.377454|width=7|height=9|layout=snake|direction=horizontal
Traceback (most recent call last):
  File "/usr/local/bin/ashlar", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/ashlar/scripts/ashlar.py", line 226, in main
    return process_single(
  File "/usr/local/lib/python3.10/dist-packages/ashlar/scripts/ashlar.py", line 254, in process_single
    reader = build_reader(filepaths[0], barrel_correction, plate_well=plate_well)
  File "/usr/local/lib/python3.10/dist-packages/ashlar/scripts/ashlar.py", line 377, in build_reader
    reader = reader_class(path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ashlar/fileseries.py", line 210, in __init__
    self.metadata = FileSeriesMetadata(
  File "/usr/local/lib/python3.10/dist-packages/ashlar/fileseries.py", line 88, in __init__
    self._enumerate_tiles()
  File "/usr/local/lib/python3.10/dist-packages/ashlar/fileseries.py", line 118, in _enumerate_tiles
    path = self.path / self.filename(0, 0)
  File "/usr/local/lib/python3.10/dist-packages/ashlar/fileseries.py", line 191, in filename
    well, series = self.all_series[self.active_series[series]]
IndexError: range object index out of range

Any help would be greatly appreciated.

Thank you

**Comment by jmuhlich** [comment]
The fileseries code does not yet have good error handling, but from experience I know the error you're seeing would typically happen when the specified directory doesn't have any files that match your pattern at all. Can you run this command to verify whether `/input` in the container is mapped to where you expect it to be? It should output a listing of your tif files:
`docker run -v %cd%:/input -it labsyspharm/ashlar:latest ls -l /input`

(I replied on image.sc too but we we can discuss here, whatever you prefer.)
