### ISSUE TITLE
Run ashlar on PhenoCyler-Fusion format data

### ISSUE THREAD

**Issue by liuyang2006** [labsyspharm/ashlar#211]
Can I use ashlar on PhenoCyler-Fusion format data (*.qptiff) ? When I run it on my data, I have following errors:

Codes:
`ashlar FV_UC-01.qptiff -m 30 -o .`

Error message:
```
Stitching and registering input images
Cycle 0:
    reading FV_UC-01.qptiff
WARNING: Stage coordinates undefined; falling back to (0, 0).
Traceback (most recent call last):
  File "/usr/local/bin/ashlar", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/ashlar/scripts/ashlar.py", line 226, in main
    return process_single(
  File "/usr/local/lib/python3.10/dist-packages/ashlar/scripts/ashlar.py", line 262, in process_single
    edge_aligner.run()
  File "/usr/local/lib/python3.10/dist-packages/ashlar/reg.py", line 505, in run
    self.check_overlaps()
  File "/usr/local/lib/python3.10/dist-packages/ashlar/reg.py", line 527, in check_overlaps
    for t1, t2 in self.neighbors_graph.edges
  File "/usr/local/lib/python3.10/dist-packages/ashlar/reg.py", line 473, in neighbors_graph
    max_distance = aligner.metadata.size.max() + 1
  File "/usr/local/lib/python3.10/dist-packages/ashlar/reg.py", line 108, in size
    raise ValueError("Image series must all have the same dimensions")
ValueError: Image series must all have the same dimensions
```

**Comment by jmuhlich** [comment]
No, that qptiff is already stitched and registered. You would need to obtain the raw unprocessed image tiles from each cycle for use with Ashlar. Akoya has not historically provided access to that data but I have heard a lot of customers have been starting to request it. It can't hurt to ask... :)

**Comment by jmuhlich** [comment]
If you can get raw unprocessed tiles please feel free to re-open this issue so we can proceed.
