### ISSUE TITLE
μm not a supported value of UnitsLength

### ISSUE THREAD

**Issue by lukaslcf** [labsyspharm/ashlar#219]
I was following this forum thread on image.sc: https://forum.image.sc/t/microscope-image-stitching-in-python/75871/11

Yu An Chen mentioned that I can use a separate ome file to reduce pixel duplication in the ome-metadata. I implemented that in my code generated the following ome file, placed in the same folder as rest of my tiff files.

OME File: [test.companion.ome.txt](https://github.com/user-attachments/files/15659560/test.companion.ome.txt)

However, when I try to run `ashlar .\test.companion.ome`, I receive the following error:

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\qtpy\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\qtpy\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\qtpy\Scripts\ashlar.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\envs\qtpy\lib\site-packages\ashlar\scripts\ashlar.py", line 226, in main
    return process_single(
  File "C:\ProgramData\Anaconda3\envs\qtpy\lib\site-packages\ashlar\scripts\ashlar.py", line 254, in process_single
    reader = build_reader(filepaths[0], barrel_correction, plate_well=plate_well)
  File "C:\ProgramData\Anaconda3\envs\qtpy\lib\site-packages\ashlar\scripts\ashlar.py", line 377, in build_reader
    reader = reader_class(path, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\qtpy\lib\site-packages\ashlar\reg.py", line 400, in __init__
    self.metadata = BioformatsMetadata(self.path)
  File "C:\ProgramData\Anaconda3\envs\qtpy\lib\site-packages\ashlar\reg.py", line 211, in __init__
    self._init_metadata()
  File "C:\ProgramData\Anaconda3\envs\qtpy\lib\site-packages\ashlar\reg.py", line 236, in _init_metadata
    self._reader.setId(self.path)
  File "jnius\jnius_export_class.pxi", line 1163, in jnius.JavaMultipleMethod.__call__
  File "jnius\jnius_export_class.pxi", line 877, in jnius.JavaMethod.__call__
  File "jnius\jnius_export_class.pxi", line 971, in jnius.JavaMethod.call_method
  File "jnius\jnius_utils.pxi", line 79, in jnius.check_exception
jnius.JavaException: JVM exception occurred: loci.common.services.ServiceException: ome.xml.model.enums.EnumerationException: '�m' not a supported value of 'class ome.xml.model.enums.UnitsLength' loci.formats.FormatException
```

The suspicious character in question is μ (mu, the greek letter for micro).

This error occured right after reading the ome file.

Thanks in advance for looking into this.

Additional information:
OS: Windows 10
<details>
<summary> Conda Enviornment </summary>
<code>
# packages in environment at C:\ProgramData\Anaconda3\envs\qtpy:
#
# Name                    Version                   Build  Channel
_libavif_api              1.0.4                h57928b3_4    conda-forge
aicsimageio               4.9.3                    pypi_0    pypi
aicspylibczi              3.0.5                    pypi_0    pypi
annotated-types           0.6.0           py310haa95532_0
ansicon                   1.89.0          py310h5588dad_7    conda-forge
aom                       3.9.0                he0c23c2_0    conda-forge
asciitree                 0.3.3                    pypi_0    pypi
ashlar                    1.18.0                   pypi_0    pypi
astroid                   2.12.13                  pypi_0    pypi
asttokens                 2.0.5              pyhd3eb1b0_0
black                     24.4.2          py310h5588dad_0    conda-forge
blessed                   1.20.0                   pypi_0    pypi
blosc                     1.21.5               hbd69f2e_1    conda-forge
brotli                    1.1.0                hcfcfb64_1    conda-forge
brotli-bin                1.1.0                hcfcfb64_1    conda-forge
brotli-python             1.0.9           py310hd77b12b_8
bzip2                     1.0.8                hcfcfb64_5    conda-forge
c-blosc2                  2.14.4               h183a6f4_1    conda-forge
ca-certificates           2024.6.2             h56e8100_0    conda-forge
certifi                   2024.6.2        py310haa95532_0
charls                    2.4.2                h1537add_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     7.1.2                    pypi_0    pypi
click-default-group       1.2.2           py310haa95532_0
cloudpickle               2.2.0                    pypi_0    pypi
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.2.1           py310haa95532_0
contourpy                 1.0.6                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cytoolz                   0.12.3          py310h8d17308_0    conda-forge
dask                      2022.11.0                pypi_0    pypi
dask-core                 2024.5.2           pyhd8ed1ab_0    conda-forge
dav1d                     1.2.1                h2bbff1b_0
dearpygui                 1.8.0                    pypi_0    pypi
debugpy                   1.6.7           py310hd77b12b_0
decorator                 5.1.1              pyhd3eb1b0_0
dill                      0.3.6                    pypi_0    pypi
dnspython                 2.2.1                    pypi_0    pypi
docformatter              1.7.5              pyhd8ed1ab_0    conda-forge
elementpath               2.5.3                    pypi_0    pypi
email-validator           1.3.0                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
exceptiongroup            1.2.0              pyhd8ed1ab_2    conda-forge
executing                 0.8.3              pyhd3eb1b0_0
fasteners                 0.18                     pypi_0    pypi
flake8                    7.0.0              pyhd8ed1ab_0    conda-forge
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               hdaf720e_2    conda-forge
fsspec                    2022.11.0                pypi_0    pypi
giflib                    5.2.2                h64bf75a_0    conda-forge
glib                      2.80.2               h0df6a38_0    conda-forge
glib-tools                2.80.2               h2f9d560_0    conda-forge
grpcio                    1.50.0                   pypi_0    pypi
grpcio-tools              1.50.0                   pypi_0    pypi
gst-plugins-base          1.24.4               hba88be7_0    conda-forge
gstreamer                 1.24.4               h5006eae_0    conda-forge
icu                       73.2                 h63175ca_0    conda-forge
idna                      3.7             py310haa95532_0
imagecodecs               2022.9.26                pypi_0    pypi
imageio                   2.34.1             pyh4b66e23_0    conda-forge
importlib-metadata        7.0.1           py310haa95532_0
importlib_metadata        7.0.1                hd8ed1ab_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
intel-openmp              2024.1.0           h57928b3_965    conda-forge
ipykernel                 6.28.0          py310haa95532_0
ipython                   8.20.0          py310haa95532_0
isort                     5.10.1                   pypi_0    pypi
jedi                      0.18.1          py310haa95532_1
jinja2                    3.1.4           py310haa95532_0
jinxed                    1.2.1              pyh31a35d3_0    conda-forge
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.0           py310haa95532_0
jupyter_core              5.5.0           py310haa95532_0
jxrlib                    1.1                  he774522_2
kiwisolver                1.4.4                    pypi_0    pypi
krb5                      1.21.2               heb0366b_0    conda-forge
lazy-object-proxy         1.8.0                    pypi_0    pypi
lcms2                     2.16                 h67d730c_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libaec                    1.1.3                h63175ca_0    conda-forge
libavif16                 1.0.4                hac688ae_4    conda-forge
libblas                   3.9.0              22_win64_mkl    conda-forge
libbrotlicommon           1.1.0                hcfcfb64_1    conda-forge
libbrotlidec              1.1.0                hcfcfb64_1    conda-forge
libbrotlienc              1.1.0                hcfcfb64_1    conda-forge
libcblas                  3.9.0              22_win64_mkl    conda-forge
libclang13                18.1.6          default_hf64faad_0    conda-forge
libdeflate                1.20                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.80.2               h0df6a38_0    conda-forge
libhwloc                  2.10.0          default_h8125262_1001    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libintl                   0.22.5               h5728263_2    conda-forge
libintl-devel             0.22.5               h5728263_2    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
liblapack                 3.9.0              22_win64_mkl    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.43               h19919ed_0    conda-forge
libsodium                 1.0.18               h62dcd97_0
libsqlite                 3.45.3               hcfcfb64_0    conda-forge
libtiff                   4.6.0                hddb2be6_3    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp-base              1.4.0                hcfcfb64_0    conda-forge
libxcb                    1.15                 hcd874cb_0    conda-forge
libxml2                   2.12.7               h283a6d9_0    conda-forge
libxslt                   1.1.39               h3df6e99_0    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
libzopfli                 1.0.3                ha925a31_0
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lxml                      4.9.1                    pypi_0    pypi
lz4-c                     1.9.4                h2bbff1b_1
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.1.3           py310h2bbff1b_0
matplotlib                3.6.2                    pypi_0    pypi
matplotlib-base           3.8.4           py310hadb10a8_2    conda-forge
matplotlib-inline         0.1.6           py310haa95532_0
mccabe                    0.7.0              pyhd8ed1ab_0    conda-forge
mkl                       2024.1.0           h66d3029_692    conda-forge
msgpack-python            1.0.8           py310hc19bc0b_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy                      1.10.0          py310ha8f682b_0    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
nest-asyncio              1.6.0           py310haa95532_0
networkx                  3.3                pyhd8ed1ab_1    conda-forge
numcodecs                 0.10.2                   pypi_0    pypi
numpy                     1.26.4          py310hf667824_0    conda-forge
ome-types                 0.5.1                    pypi_0    pypi
opencv-contrib-python-headless 4.7.0.72                 pypi_0    pypi
openjdk                   11.0.23              h57928b3_0    conda-forge
openjpeg                  2.5.2                h3d672ee_0    conda-forge
openssl                   3.3.1                h2466b09_0    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pandas                    2.1.0                    pypi_0    pypi
parso                     0.8.3              pyhd3eb1b0_0
partd                     1.3.0                    pypi_0    pypi
pathspec                  0.12.1             pyhd8ed1ab_0    conda-forge
pcre2                     10.43                h17e33f8_0    conda-forge
pillow                    9.3.0                    pypi_0    pypi
pint                      0.20.1                   pypi_0    pypi
pip                       24.0               pyhd8ed1ab_0    conda-forge
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_0    conda-forge
ply                       3.11               pyhd8ed1ab_2    conda-forge
prompt-toolkit            3.0.43          py310haa95532_0
prompt_toolkit            3.0.43               hd3eb1b0_0
protobuf                  4.21.9                   pypi_0    pypi
psutil                    5.9.8           py310h8d17308_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pure_eval                 0.2.2              pyhd3eb1b0_0
pycodestyle               2.11.1             pyhd8ed1ab_0    conda-forge
pydantic                  1.10.2                   pypi_0    pypi
pydantic-compat           0.1.2              pyhd8ed1ab_0    conda-forge
pydantic-core             2.14.6          py310h062c2fa_0
pyflakes                  3.2.0              pyhd8ed1ab_0    conda-forge
pygments                  2.15.1          py310haa95532_1
pyjnius                   1.6.1           py310h406e284_0    conda-forge
pylint                    2.15.8                   pypi_0    pypi
pymea                     0.0.1                    pypi_0    pypi
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.9          py310h1fd54f2_5    conda-forge
pyqt5-sip                 12.12.2         py310h00ffb61_5    conda-forge
pyside6                   6.5.0                    pypi_0    pypi
pyside6-addons            6.5.0                    pypi_0    pypi
pyside6-essentials        6.5.0                    pypi_0    pypi
pysocks                   1.7.1           py310haa95532_0
pytest                    8.2.1              pyhd8ed1ab_0    conda-forge
python                    3.10.14         h4de0772_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python-dotenv             0.21.0                   pypi_0    pypi
python_abi                3.10                    4_cp310    conda-forge
pytz                      2022.6                   pypi_0    pypi
pywavelets                1.6.0                    pypi_0    pypi
pywin32                   305             py310h2bbff1b_0
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     25.1.2          py310hd77b12b_0
qt-main                   5.15.8              hcef0176_21    conda-forge
rav1e                     0.6.6                h975169c_2    conda-forge
requests                  2.32.2          py310haa95532_0
resource-backed-dask-array 0.1.0                    pypi_0    pypi
ruff                      0.3.5           py310h36a85e1_0
scikit-image              0.19.3          py310h1c4a608_2    conda-forge
scikit-learn              1.5.0           py310hf2a6c47_1    conda-forge
scipy                     1.13.1          py310h46043a1_0    conda-forge
setuptools                69.5.1             pyhd8ed1ab_0    conda-forge
shiboken6                 6.5.0                    pypi_0    pypi
sip                       6.7.12          py310h00ffb61_0    conda-forge
six                       1.16.0             pyhd3eb1b0_1
snappy                    1.2.0                hfb803bf_1    conda-forge
stack_data                0.2.0              pyhd3eb1b0_0
svt-av1                   2.1.0                he0c23c2_0    conda-forge
symlink-exe-runtime       1.0                  hcfcfb64_0    conda-forge
tbb                       2021.12.0            hc790b64_1    conda-forge
threadpoolctl             3.5.0              pyhc1e730c_0    conda-forge
tifffile                  2024.5.22          pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.11.6                   pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
toposort                  1.10               pyhd8ed1ab_0    conda-forge
tornado                   6.3.3           py310h2bbff1b_0
traitlets                 5.7.1           py310haa95532_0
typing-extensions         4.11.0               hd8ed1ab_0    conda-forge
typing_extensions         4.11.0             pyha770c72_0    conda-forge
tzdata                    2023.3                   pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
unicodedata2              15.1.0          py310h8d17308_0    conda-forge
untokenize                0.1.1                      py_0    conda-forge
urllib3                   2.2.1           py310haa95532_0
vc                        14.3                ha32ba9b_20    conda-forge
vc14_runtime              14.38.33135         h835141b_20    conda-forge
vs2015_runtime            14.38.33135         h22015db_20    conda-forge
wcwidth                   0.2.5              pyhd3eb1b0_0
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
win_inet_pton             1.1.0           py310haa95532_0
wrapt                     1.14.1                   pypi_0    pypi
xarray                    2022.11.0                pypi_0    pypi
xmlschema                 1.11.3                   pypi_0    pypi
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xsdata                    24.3.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zarr                      2.13.3                   pypi_0    pypi
zeromq                    4.3.5                hd77b12b_0
zfp                       1.0.1                h63175ca_0    conda-forge
zipp                      3.17.0          py310haa95532_0
zlib-ng                   2.0.7                h2bbff1b_0
zstd                      1.5.6                h0ea2cb4_0    conda-forge
</code>
</details>

**Comment by lukaslcf** [comment]
I tried converting the file to utf-8, and it seems to solve the issue. The problem is that tifffile.imwrite() defaults to outputting ANSI files.
