### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Noorulhuda90** [labsyspharm/ashlar#226]
I am unable to install it Pip is not working conda is not working and There is no document available on how to run it inside a docker. Can anyone help ? I am getting this error after setting up conda envirnment.

 python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /tmp/pip-install-j7v3d4gg/ashlar_ebf1d54e34214b36a970cdd602bdf9cd/versioneer.py:423: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-j7v3d4gg/ashlar_ebf1d54e34214b36a970cdd602bdf9cd/setup.py", line 24, in <module>
          VERSION = versioneer.get_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-j7v3d4gg/ashlar_ebf1d54e34214b36a970cdd602bdf9cd/versioneer.py", line 1483, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-j7v3d4gg/ashlar_ebf1d54e34214b36a970cdd602bdf9cd/versioneer.py", line 1415, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-j7v3d4gg/ashlar_ebf1d54e34214b36a970cdd602bdf9cd/versioneer.py", line 344, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by moataz-youssef** [comment]
I am having the same issues when trying to install Ashlar in a conda environment (Anaconda distribution running on Windows 10).

**Comment by Phillip-Miller** [comment]
did you find a solution?

**Comment by moataz-youssef** [comment]
Nope. I tried the same steps on 3 different systems with different configurations and everytime the same error. I guess the package is damaged or something.

**Comment by jmuhlich** [comment]
Sorry, this is a problem with python 3.12 compatibility in the versions of ashlar currently available via pip. You can either create a virtual environment with python 3.11, or you can use python 3.12 and install directly from github where we've fixed the problem:
```
pip install git+https://github.com/jmuhlich/ashlar.git
```
I will try to release an updated version to pypi soon.

**Comment by Noorulhuda90** [comment]
It worked with above installation command for me. 

Can you help me how the data must look like ? like if we have tiles in 6x11 mosaic. Can we define it is 6x11 ?

**Comment by jmuhlich** [comment]
Sure, I will need to see a list of some example filenames, and it may be helpful to know what microscope you are using.

**Comment by jmuhlich** [comment]
> I will try to release an updated version to pypi soon.
Ashlar 1.19.0 is now available with the fix for Python 3.12. Please try to install it and let me know whether it works for you.

**Comment by Noorulhuda90** [comment]
For file names they are like X00Y00 to define position in the mosaic. But to use in ImageJ I have also named it as image_1 to image_66.

**Comment by jmuhlich** [comment]
Sorry for the slow response! If you have names like `imageX00Y00.tif`, you can use the "filepattern" reader. Adjust the pattern in the example below to match your actual filenames, with `{col:2}` and `{row:2}` standing in for the actual numeric X and Y coordinates in the filename. If your numbers have 3 digits you can use `:3` instead of `:2`. You will also need to specify the pixel size in microns (I will use 0.5 here as an example) and the fraction of overlap between neighboring tiles (I will use 0.1 as an example, i.e. 10% overlap). First, use our `preview_slide` tool to visualize the tile positions and make sure everything is right:
```bash
preview_slide -l -n -b "filepattern|/path/to/images|pattern=imageX{col:2}Y{row:2}.tif|pixel_size=0.5|overlap=0.1"
```
You can add `--flip-y` to the command if the tiles seem like they need to be flipped vertically to line up properly. There is also `--flip-x` but it's not usually needed. Once you get the preview looking good, run `ashlar` with the same filepattern string and the same `--flip-...` arguments you chose. Do not pass `-l -n -b` to ashlar.
