### ISSUE TITLE
Output array size too large for JVM

### ISSUE THREAD

**Issue by VolkerH** [labsyspharm/ashlar#94]
Hi @jmuhlich 

as per your suggestion in a different repo I I just gave this a spin. Trying to stitch a whole slide acquisition
in a single .nd2 file I run into errors with output size:

```
(/home/jovyan/shared_volker/ashlar) jovyan@43e3f12000b3:~/Desktop$ JAVA_TOOL_OPTIONS="-Xmx20G"  ashlar whole_slide_scan_large_image.nd2 -c 0
Picked up JAVA_TOOL_OPTIONS: -Xmx20G
Cycle 0:
    reading whole_slide_scan_large_image.nd2
WARNING: Stage coordinates' measurement unit is undefined; assuming μm.

    Channel 0:
        merging tile 1/1Traceback (most recent call last):
  File "/home/jovyan/shared_volker/ashlar/bin/ashlar", line 8, in <module>
    sys.exit(main())
  File "/home/jovyan/shared_volker/ashlar/lib/python3.7/site-packages/ashlar/scripts/ashlar.py", line 174, in main
    args.quiet
  File "/home/jovyan/shared_volker/ashlar/lib/python3.7/site-packages/ashlar/scripts/ashlar.py", line 219, in process_single
    mosaic.run()
  File "/home/jovyan/shared_volker/ashlar/lib/python3.7/site-packages/ashlar/reg.py", line 1085, in run
    tile_image = self.aligner.reader.read(c=channel, series=tile)
  File "/home/jovyan/shared_volker/ashlar/lib/python3.7/site-packages/ashlar/reg.py", line 420, in read
    img = self.reader.read(series, c)
  File "/home/jovyan/shared_volker/ashlar/lib/python3.7/site-packages/ashlar/reg.py", line 397, in read
    byte_array = self.metadata._reader.openBytes(index)
  File "jnius/jnius_export_class.pxi", line 1047, in jnius.JavaMultipleMethod.__call__
  File "jnius/jnius_export_class.pxi", line 769, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 856, in jnius.JavaMethod.call_method
  File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: JVM exception occurred: Array size too large: 70714 x 28428 x 2
(/home/jovyan/shared_volker/ashlar) jovyan@43e3f12000b3:~/Desktop$ 
```

The output array size seems quite realistic for this problem: 70714 x 28428 x 2
The machine has plenty of RAM (>64 Gbyte). Not sure whether I should be doing something differently or whether I am hitting a limtation here.

**Comment by jmuhlich** [comment]
It looks like your ND2 file is pre-stitched -- note the beginning of the Ashlar output before the exception:
```
merging tile 1/1
```
You would expect to see a number much larger than 1 if the file contained individual tiles. You'll need to provide the raw un-stitched tiles for Ashlar to be useful, but unfortunately I don't think there is a clean way to do this for ND2 files yet. Let's chat offline a bit about your data and what the options are, and I'll update this ticket later with the resolution.

**Comment by VolkerH** [comment]
Ah, I thought this was an nd2 containing individual tiles, but I didn't check in detail, you are probably right.
This was one of the few nd2 files I had lying around, usually I have collections of tiff files plus an accompanying `.csv` file with the stage coordinates for each tiff file. This is a bit of a legacy protocol being used in the group that is based on the Nikon Jobs functionality.

I sent you an email, and yes ... would be happy to discuss offline.

**Comment by VolkerH** [comment]
I think this can be closed
