### ISSUE TITLE
Error on mac and linux out of the blue

### ISSUE THREAD

**Issue by alcrevenna** [labsyspharm/ashlar#98]
I have been testing ashlar on linux and was working fine, today I had this error (even trying to run the same thing i did yesterday). Then I installed ashlar on my mac and have the same error. 

(ashlar) mac-microscopy1:stitching_registration alvarocrevenna$ ashlar “fileseries|/Users/alvarocrevenna/Documents/Data/2021/stitching_registration|pattern=test_{series}.tif|overlap=0.05|layout=raster|width=5|height=6” --output-channels 0 --maximum-shift 50 --filter-sigma 1 --pyramid -f ashlar_ouput_result.ome.tiff
-bash: /Users/alvarocrevenna/Documents/Data/2021/stitching_registration: is a directory
-bash: --output-channels: command not found
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ashlar/bin/ashlar", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/ashlar/lib/python3.7/site-packages/ashlar/scripts/ashlar.py", line 174, in main
    args.quiet
  File "/opt/anaconda3/envs/ashlar/lib/python3.7/site-packages/ashlar/scripts/ashlar.py", line 202, in process_single
    reader = build_reader(filepaths[0], plate_well=plate_well)
  File "/opt/anaconda3/envs/ashlar/lib/python3.7/site-packages/ashlar/scripts/ashlar.py", line 328, in build_reader
    reader = reader_class(path, **kwargs)
  File "/opt/anaconda3/envs/ashlar/lib/python3.7/site-packages/ashlar/reg.py", line 391, in __init__
    self.metadata = BioformatsMetadata(self.path)
  File "/opt/anaconda3/envs/ashlar/lib/python3.7/site-packages/ashlar/reg.py", line 207, in __init__
    self._init_metadata()
  File "/opt/anaconda3/envs/ashlar/lib/python3.7/site-packages/ashlar/reg.py", line 231, in _init_metadata
    self._reader.setId(self.path)
  File "jnius/jnius_export_class.pxi", line 769, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 863, in jnius.JavaMethod.call_method
  File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: JVM exception occurred: “fileseries (No such file or directory)
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe

Any idea?
thanks, Alvaro

**Comment by jmuhlich** [comment]
This is not an Ashlar problem but rather a Bash one: Your plain double-quotes have somehow been turned into "fancy quotes" which cause all sorts of havoc with the Bash command line. Did you use Word or another word processor to keep your notes? Apps like that often make auto-corrections that are actively harmful for code and command line stuff. Try this corrected command:
```bash
ashlar "fileseries|/Users/alvarocrevenna/Documents/Data/2021/stitching_registration|pattern=test_{series}.tif|overlap=0.05|layout=raster|width=5|height=6" --output-channels 0 --maximum-shift 50 --filter-sigma 1 --pyramid -f ashlar_ouput_result.ome.tiff
```

**Comment by alcrevenna** [comment]
Dear Jeremy,

  thanks for the feedback. I have now used your code snippet as well as I switched to atom to see those fancy quotes. I still get the rest of the error, which seems to come from anaconda. And that part is the same error I get in linux.

best,

Alvaro

`(ashlar) mac-microscopy1:stitching_registration alvarocrevenna$ ashlar "fileseries|/Users/alvarocrevenna/Documents/Data/2021/stitching_registration|pattern=test_{series}.tif|overlap=0.05|layout=raster|width=5|height=6"  --output-channels 0 --maximum-shift 50 --filter-sigma 1 --pyramid -f ashlar_ouput_result.ome.tiff
Cycle 0:
    reading fileseries|/Users/alvarocrevenna/Documents/Data/2021/stitching_registration|pattern=test_{series}.tif|overlap=0.05|layout=raster|width=5|height=6
    quantifying alignment error 1000/1000
    aligning edge 5/49/opt/anaconda3/envs/ashlar/lib/python3.7/site-packages/skimage/feature/register_translation.py:104: RuntimeWarning: invalid value encountered in cdouble_scalars
  (src_amp * target_amp)
    aligning edge 49/49
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ashlar/bin/ashlar", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/ashlar/lib/python3.7/site-packages/ashlar/scripts/ashlar.py", line 174, in main
    args.quiet
  File "/opt/anaconda3/envs/ashlar/lib/python3.7/site-packages/ashlar/scripts/ashlar.py", line 208, in process_single
    edge_aligner.run()
  File "/opt/anaconda3/envs/ashlar/lib/python3.7/site-packages/ashlar/reg.py", line 479, in run
    self.build_spanning_tree()
  File "/opt/anaconda3/envs/ashlar/lib/python3.7/site-packages/ashlar/reg.py", line 612, in build_spanning_tree
    paths = nx.single_source_dijkstra_path(cc, center).values()
  File "/opt/anaconda3/envs/ashlar/lib/python3.7/site-packages/networkx/algorithms/shortest_paths/weighted.py", line 299, in single_source_dijkstra_path
    return multi_source_dijkstra_path(G, {source}, cutoff=cutoff, weight=weight)
  File "/opt/anaconda3/envs/ashlar/lib/python3.7/site-packages/networkx/algorithms/shortest_paths/weighted.py", line 543, in multi_source_dijkstra_path
    length, path = multi_source_dijkstra(G, sources, cutoff=cutoff, weight=weight)
  File "/opt/anaconda3/envs/ashlar/lib/python3.7/site-packages/networkx/algorithms/shortest_paths/weighted.py", line 731, in multi_source_dijkstra
    G, sources, weight, paths=paths, cutoff=cutoff, target=target
  File "/opt/anaconda3/envs/ashlar/lib/python3.7/site-packages/networkx/algorithms/shortest_paths/weighted.py", line 840, in _dijkstra_multisource
    raise ValueError("Contradictory paths found:", "negative weights?")
ValueError: ('Contradictory paths found:', 'negative weights?')`

**Comment by alcrevenna** [comment]
I just wanted to leave the solution here:
I was testing ASHLAR where I split an image of 9000 x 7500 pixels in tiles of 1500 pixels with an overlap of 75 pixels. Somehow giving overlap of 0.05 was creating problems. If I use 0.06 or 0.045 works and the stitching results are good.
Trying ASHLAR within a jupyter notebook also helped me narrow down the problem to the stitching and not any other step.
thanks for creating this tool.
Alvaro

**Comment by jmuhlich** [comment]
Thanks for the update. We definitely need better error messages and a better way to debug and explore the parameter values.
